---

- name: Pull an Zebrunner MCloud device image
  shell: docker pull "{{ DEVICE_IMAGE }}:{{ DEVICE_VERSION }}"

- name: Pull an Zebrunner Appium image
  shell: docker pull "{{ APPIUM_IMAGE }}:{{ APPIUM_VERSION }}"

- name: Pull an Zebrunner Uploader image
  shell: docker pull "{{ UPLOADER_IMAGE }}:{{ UPLOADER_VERSION }}"

- name: Create infra network if absent
  shell: docker network inspect "{{ STF_DOCKER_NETWORK }}" >/dev/null 2>&1 || docker network create "{{ STF_DOCKER_NETWORK }}"
