version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  mcloud-grid:
    image: "zebrunner/mcloud-grid:${TAG_SELENIUM_HUB}"
    container_name: mcloud-grid
    env_file:
     - variables.env
    environment:
#     4min session wait timeout as 5 min is configured on NGiNX
     - GRID_NEW_SESSION_WAIT_TIMEOUT=240000
     - GRID_TIMEOUT=60000
     - GRID_BROWSER_TIMEOUT=60000
#     - JAVA_OPTS=-Dselenium.LOGGER.level=FINEST
    ports:
     - "4444:4444"
    restart: always
  stf-rethinkdb-proxy:
    image: "openstf/ambassador:latest"
    container_name: stf-rethinkdb-proxy
    env_file:
     - variables.env
    environment:
     - RETHINKDB_PORT_28015_TCP=${TCP_RETHINK_DB}
    restart: always
  stf-processor001:
    image: "zebrunner/stf:${TAG_STF}"
    container_name: stf-processor001
    env_file:
     - variables.env
    command: stf processor proc001 --connect-app-dealer ${CONNECT_APP_DEALER} --connect-dev-dealer ${CONNECT_DEV_DEALER}
    depends_on:
     - "stf-rethinkdb-proxy"
    restart: always
