---

- name: copy script to launch container with appium for device
  template: src=zebrunner-farm dest=/usr/local/bin/ mode=755

- name: copy rules to launch script on connected device
  template: src=90_mcloud.rules dest=/etc/udev/rules.d/

- name: copy devices details
  template: src=mcloud-devices.txt dest=/usr/local/bin/

- name: restart udev
  command: udevadm control --reload

- stat: path={{ P12FILE }}
  register: p12

- name: Generate docker volume and copy p12 to /opt/zebrunner/mcloud.p12
  shell: docker run --rm -v "{{ P12FILE }}:/var/tmp/mcloud.p12" -v mcloud-storage-volume:/opt/zebrunner "ubuntu:16.04" bash -c "cp /var/tmp/mcloud.p12 /opt/zebrunner/"
  when: p12.stat.exists
